- name: Asegurar dependencias
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Crear directorio de llaves de apt
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar la llave GPG de Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Agregar el repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: Instalar Docker Engine, CLI, containerd y plugin Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Habilitar y arrancar el servicio Docker
  service:
    name: docker
    state: started
    enabled: yes
