## ansible-playbook -i inventory.yml 02-debian/tools/k8s/install_k8s-multi-arquitectura.yml --ask-pass

---
- name: Instalar Kubernetes en Debian 13 ARM64
  hosts: k8s_servers
  become: true

  tasks:

    - name: Instalar dependencias necesarias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - util-linux
        state: present
        update_cache: yes

    - name: Desactivar swap (requerido por k8s)
      command: sudo swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Comentar swap en fstab
      replace:
        path: /etc/fstab
        regexp: '(^.*swap.*$)'
        replace: '# \1'

    - name: Crear directorio para llaves
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar clave GPG de Kubernetes
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Agregar repositorio de Kubernetes (multi-arquitectura, soporta arm64)
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
        state: present
        filename: kubernetes

    - name: Actualizar cache de paquetes tras agregar repo
      apt:
        update_cache: yes

    - name: Instalar kubelet, kubeadm y kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Poner kubelet, kubeadm y kubectl en hold
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Habilitar kubelet en systemd
      systemd:
        name: kubelet
        enabled: yes
