---
# Tareas para una sola VM de Talos (Rutas organizadas)

- name: "Verificar si la VM {{ vm_item.name }} ya existe"
  shell: "virsh list --all | grep -w {{ vm_item.name }}"
  register: vm_exists
  failed_when: false
  changed_when: false

- name: "Crear disco QCOW2 en carpeta /vms para {{ vm_item.name }}"
  shell: |
    qemu-img create -f qcow2 -b {{ vms_iso_pool }}/talos-base.raw -F raw {{ vms_disk_pool }}/{{ vm_item.name }}.qcow2 {{ vm_item.disk_size }}
  when: vm_exists.rc != 0

- name: "Crear segundo disco QCOW2 para {{ vm_item.name }}"
  shell: |
    qemu-img create -f qcow2 {{ vms_disk_pool }}/{{ vm_item.name }}-data.qcow2 {{ vm_item.disk_size_2 }}
  when: vm_exists.rc != 0 and vm_item.disk_size_2 is defined

- name: "Instalar y arrancar nodo Talos {{ vm_item.name }}"
  shell: |
    virt-install \
      --name {{ vm_item.name }} \
      --memory {{ vm_item.memory }} \
      --vcpus {{ vm_item.vcpus }} \
      --disk {{ vms_disk_pool }}/{{ vm_item.name }}.qcow2,device=disk,bus=virtio \
      {{ '--disk ' ~ vms_disk_pool ~ '/' ~ vm_item.name ~ '-data.qcow2,device=disk,bus=virtio' if vm_item.disk_size_2 is defined else '' }} \
      --os-variant fedora31 \
      --virt-type kvm \
      --graphics spice \
      --video qxl \
      --channel spicevmc \
      --network bridge=br0,model=virtio \
      --import \
      --noautoconsole

  when: vm_exists.rc != 0
