## ansible-playbook -i inventory.yml 02-debian/networking/set_static_ip.yml --ask-pass
## Server fisico - ajustar interfaces en la plantilla de interfaces.j2 cuando sea virtual

---
- name: Configurar IP est치tica en servidores Debian
  hosts: k8s_servers
  become: yes  # Ejecutar como superusuario
  vars:
    static_ip: "{{ hostvars[inventory_hostname].static_ip }}"
    gateway: "{{ hostvars[inventory_hostname].gateway }}"  # Cambia esto con la puerta de enlace de tu red
    dns_server: "{{ hostvars[inventory_hostname].dns_server }}"     # Cambia esto con tu servidor DNS
  tasks:
    - name: Configurar IP est치tica usando archivo Interfaces
      template:
        src: "interfaces.j2"  # Archivo de plantilla Jinja2
        dest: "/etc/network/interfaces"
      notify:
        - aplicar configuraci칩n de red

  handlers:
    - name: aplicar configuraci칩n de red
      command: systemctl restart networking



