# ansible-playbook -i inventory.yml ubuntu-server/02-networking/disable-network-config.yml --ask-become-pass
---
- name: Crear carpeta, copiar scripts, dar permisos y crear cron
  hosts: servidores
  become: true
  vars:
    destino: /etc/auto
    cron_user: root
    cron_minute: "*/5"  # cada 5 minutos, cambia si lo necesitas

  tasks:
    - name: Crear carpeta auto
      file:
        path: "{{ destino }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copiar scripts al servidor
      copy:
        src: scripts/
        dest: "{{ destino }}/"
        mode: '0755'
        owner: root
        group: root
      notify: "Reiniciar cron si es necesario"

    - name: Dar permisos de ejecución a los scripts
      file:
        path: "{{ item.path }}"
        mode: '0755'
      loop: "{{ lookup('ansible.builtin.find', destino, recurse=True, patterns='*.sh', wantlist=True) }}"

    - name: Crear tareas en cron para cada script
      cron:
        name: "Ejecutar {{ item.path }}"
        minute: "{{ cron_minute }}"
        user: "{{ cron_user }}"
        job: "{{ item.path }}"
      loop: "{{ lookup('ansible.builtin.find', destino, recurse=True, patterns='*.sh', wantlist=True) }}"
