## ansible-playbook -i inventory.yml 02-debian/tools/docker/install_docker-arm64.yml --ask-pass

---
- name: Instalar Docker en Debian 13
  hosts: k8s_servers
  become: true

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Instalar dependencias necesarias
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Crear directorio para llaves de Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar clave GPG de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Agregar repositorio oficial de Docker
      apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Actualizar cache de paquetes tras agregar repo
      apt:
        update_cache: yes

    - name: Instalar Docker y componentes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Habilitar y arrancar Docker
      systemd:
        name: docker
        enabled: yes
        state: started
