---
# Parámetros para las VMs de Talos (Organizado por carpetas)
vms_iso_pool: "/var/lib/libvirt/images/isos"
vms_disk_pool: "/var/lib/libvirt/images/vms"

# Corregido a .xz para la versión v1.7.5 estable
vms_base_image_url: "https://github.com/siderolabs/talos/releases/download/v1.7.5/metal-amd64.raw.xz"

vms_list:
  - name: "talos-node-cp"
    memory: 4096
    vcpus: 4
    disk_size: 40G
  - name: "talos-node-w1"
    memory: 4096
    vcpus: 4
    disk_size: 30G
    disk_size_2: 10G
  - name: "talos-node-w2"
    memory: 4096
    vcpus: 4
    disk_size: 30G
    disk_size_2: 10G
  - name: "talos-node-w3"
    memory: 4096
    vcpus: 4
    disk_size: 30G
    disk_size_2: 10G
