# ansible-playbook -i inventory.yml ubuntu-server/02-networking/set_static_ip.yml --ask-become-pass
---
- name: Configurar IP est치tica en servidores Ubuntu
  hosts: k8s_servers
  become: yes  # Ejecutar como superusuario
  vars:
    static_ip: "{{ hostvars[inventory_hostname].static_ip }}"
    gateway: "{{ hostvars[inventory_hostname].gateway }}"  # Cambia esto con la puerta de enlace de tu red
    dns_server: "{{ hostvars[inventory_hostname].dns_server }}"   # Cambia esto con tu servidor DNS
  tasks:
    - name: Configurar IP est치tica usando Netplan
      template:
        src: "netplan_static_config.j2"  # Archivo de plantilla Jinja2
        dest: "/etc/netplan/01-netcfg.yaml"
      notify:
        - aplicar configuraci칩n de red

  handlers:
    - name: aplicar configuraci칩n de red
      command: netplan apply
